### ISSUE TITLE
uploadCount instead of downloadCount limiting speed in runDownload

### ISSUE THREAD

**Issue by svasilevskiy** [minio/s3-benchmark#6]
https://github.com/minio/s3-benchmark/blob/ad0c19e0de7e1d87a000c5dca7308addec012a92/s3-benchmark.go#L279

Should be <pre>Int63n(downloadCount)</pre> here instead of uploadCount, or the downloads don't download all the objects that have been uploaded. The original wasabi/s3-benchmark uses download_count. There is probably more IO contention going on with uploadCount, since it is smaller (the upload speed is slower) leading to slower download speeds. The minio's version gives <50% download speed vs. wasabi's version run against a local MinIO instance on a MacBook Pro (1.5GB/sec vs. 3.1GB/s). Changing this line to <pre>objnum := rand.Int63n(downloadCount) + 1</pre> fixes the speed difference.

**Comment by harshavardhana** [comment]
Looks like they fixed it upstream and we never did it on our end

350dcc36 (Jeff Flowers   2017-06-09 11:39:42 -0400 226) func runDownload(thread_num int) {
350dcc36 (Jeff Flowers   2017-06-09 11:39:42 -0400 227)         for time.Now().Before(endtime) {
350dcc36 (Jeff Flowers   2017-06-09 11:39:42 -0400 228)                 atomic.AddInt32(&download_count, 1)
350dcc36 (Jeff Flowers   2017-06-09 11:39:42 -0400 229)                 objnum := rand.Int31n(upload_count) + 1

**Comment by harshavardhana** [comment]
Fixed here https://github.com/wasabi-tech/s3-benchmark/commit/2425970ca20bc38cb724c1f7cb4f2030f7d2766a

**Comment by harshavardhana** [comment]
This was a bug introduced in PR wasabi-tech@2425970 - we have the correct original code
